# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseTrain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
'''
Auth://作者 吴茜
Create date:///创建时间 2020.7.9
Update date://签入时间 2020.7.11
Discrip://此处须注明更新的详细内容
    前端代码
'''

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChososeTrainP(object):
    def setupUi(self, ChososeTrainP):
        ChososeTrainP.setObjectName("ChososeTrainP")
        ChososeTrainP.resize(1920, 1080)
        self.label = QtWidgets.QLabel(ChososeTrainP)
        self.label.setGeometry(QtCore.QRect(200, 150, 1400, 800))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.searchB = QtWidgets.QPushButton(ChososeTrainP)
        self.searchB.setGeometry(QtCore.QRect(1690, 80, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.searchB.setFont(font)
        self.searchB.setObjectName("searchB")
        self.chooseCurrentVideoB = QtWidgets.QPushButton(ChososeTrainP)
        self.chooseCurrentVideoB.setGeometry(QtCore.QRect(720, 340, 500, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.chooseCurrentVideoB.setFont(font)
        self.chooseCurrentVideoB.setObjectName("chooseCurrentVideoB")
        self.searchT = QtWidgets.QTextEdit(ChososeTrainP)
        self.searchT.setGeometry(QtCore.QRect(1070, 70, 581, 64))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.searchT.setFont(font)
        self.searchT.setObjectName("searchT")
        self.jumpToMainWindowP = QtWidgets.QPushButton(ChososeTrainP)
        self.jumpToMainWindowP.setGeometry(QtCore.QRect(60, 60, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToMainWindowP.setFont(font)
        self.jumpToMainWindowP.setObjectName("jumpToMainWindowP")

        self.retranslateUi(ChososeTrainP)
        QtCore.QMetaObject.connectSlotsByName(ChososeTrainP)

    def retranslateUi(self, ChososeTrainP):
        _translate = QtCore.QCoreApplication.translate
        ChososeTrainP.setWindowTitle(_translate("ChososeTrainP", "Form"))
        self.label.setText(_translate("ChososeTrainP", "此范围目前用于展示标准视频大小,视频信息的控件还未补全。"))
        self.searchB.setText(_translate("ChososeTrainP", "搜索"))
        self.chooseCurrentVideoB.setText(_translate("ChososeTrainP", "暂时用于点击播放视频，实现跳转的按钮"))
        self.searchT.setHtml(_translate("ChososeTrainP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747172;\">请输入视频信息</span></p></body></html>"))
        self.jumpToMainWindowP.setText(_translate("ChososeTrainP", "返回首页"))
