# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseTrain.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChososeTrainP(object):
    def setupUi(self, ChososeTrainP):
        ChososeTrainP.setObjectName("ChososeTrainP")
        ChososeTrainP.resize(1920, 1080)
        self.jumpToMainWindowP = QtWidgets.QPushButton(ChososeTrainP)
        self.jumpToMainWindowP.setGeometry(QtCore.QRect(1760, 20, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.jumpToMainWindowP.setFont(font)
        self.jumpToMainWindowP.setStyleSheet("color: rgb(252, 204, 220);\n"
"background-color: rgb(7, 33, 58);")
        self.jumpToMainWindowP.setObjectName("jumpToMainWindowP")
        self.label_2 = QtWidgets.QLabel(ChososeTrainP)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 1920, 1080))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Image/patten2.png"))
        self.label_2.setObjectName("label_2")
        self.allWidget = QtWidgets.QTabWidget(ChososeTrainP)
        self.allWidget.setGeometry(QtCore.QRect(70, 70, 1800, 950))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(22)
        self.allWidget.setFont(font)
        self.allWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.allWidget.setObjectName("allWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listWidget_1 = QtWidgets.QListWidget(self.tab)
        self.listWidget_1.setGeometry(QtCore.QRect(0, 0, 1800, 950))
        self.listWidget_1.setObjectName("listWidget_1")
        self.allWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(0, 0, 1800, 950))
        self.listWidget_2.setObjectName("listWidget_2")
        self.allWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_5)
        self.listWidget_3.setGeometry(QtCore.QRect(0, 0, 1800, 950))
        self.listWidget_3.setObjectName("listWidget_3")
        self.allWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.listWidget_4 = QtWidgets.QListWidget(self.tab_6)
        self.listWidget_4.setGeometry(QtCore.QRect(0, 0, 1800, 950))
        self.listWidget_4.setObjectName("listWidget_4")
        self.allWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.listWidget_5 = QtWidgets.QListWidget(self.tab_7)
        self.listWidget_5.setGeometry(QtCore.QRect(0, 0, 1800, 950))
        self.listWidget_5.setObjectName("listWidget_5")
        self.allWidget.addTab(self.tab_7, "")
        self.label_2.raise_()
        self.allWidget.raise_()
        self.jumpToMainWindowP.raise_()

        self.retranslateUi(ChososeTrainP)
        self.allWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ChososeTrainP)

    def retranslateUi(self, ChososeTrainP):
        _translate = QtCore.QCoreApplication.translate
        ChososeTrainP.setWindowTitle(_translate("ChososeTrainP", "Form"))
        self.jumpToMainWindowP.setText(_translate("ChososeTrainP", "返回首页"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab), _translate("ChososeTrainP", "全部"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab_2), _translate("ChososeTrainP", "健身"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab_5), _translate("ChososeTrainP", "有氧操"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab_6), _translate("ChososeTrainP", "舞蹈"))
        self.allWidget.setTabText(self.allWidget.indexOf(self.tab_7), _translate("ChososeTrainP", "拉伸"))
