# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FamilyRankList.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FamilyRankListP(object):
    def setupUi(self, FamilyRankListP):
        FamilyRankListP.setObjectName("FamilyRankListP")
        FamilyRankListP.resize(1920, 1080)
        self.imageL = QtWidgets.QLabel(FamilyRankListP)
        self.imageL.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.imageL.setText("")
        self.imageL.setPixmap(QtGui.QPixmap("../Image/patten2.png"))
        self.imageL.setObjectName("imageL")
        self.listWidget = QtWidgets.QListWidget(FamilyRankListP)
        self.listWidget.setGeometry(QtCore.QRect(250, 90, 280, 900))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(FamilyRankListP)
        self.listWidget_2.setGeometry(QtCore.QRect(670, 90, 680, 900))
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(FamilyRankListP)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1730, 150, 141, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgb(0, 201, 205);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setStyleSheet("background-color: rgb(254, 97, 148);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("background-color: rgb(252, 204, 220);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setStyleSheet("background-color: rgb(130, 156, 181);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Adobe Arabic\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(FamilyRankListP)
        self.pushButton.setGeometry(QtCore.QRect(1740, 30, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(252, 204, 220);\n"
"background-color: rgb(7, 33, 58);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(FamilyRankListP)
        QtCore.QMetaObject.connectSlotsByName(FamilyRankListP)

    def retranslateUi(self, FamilyRankListP):
        _translate = QtCore.QCoreApplication.translate
        FamilyRankListP.setWindowTitle(_translate("FamilyRankListP", "Form"))
        self.label_5.setText(_translate("FamilyRankListP", "健身区"))
        self.label_4.setText(_translate("FamilyRankListP", "有氧区"))
        self.label_2.setText(_translate("FamilyRankListP", "舞蹈区"))
        self.label_3.setText(_translate("FamilyRankListP", "拉伸"))
        self.pushButton.setText(_translate("FamilyRankListP", "返回上级"))
