# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryP(object):
    def setupUi(self, HistoryP):
        HistoryP.setObjectName("HistoryP")
        HistoryP.resize(1920, 1080)
        self.searchB = QtWidgets.QPushButton(HistoryP)
        self.searchB.setGeometry(QtCore.QRect(1720, 90, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.searchB.setFont(font)
        self.searchB.setObjectName("searchB")
        self.jumpToMainWindowP = QtWidgets.QPushButton(HistoryP)
        self.jumpToMainWindowP.setGeometry(QtCore.QRect(60, 50, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToMainWindowP.setFont(font)
        self.jumpToMainWindowP.setObjectName("jumpToMainWindowP")
        self.searchT = QtWidgets.QTextEdit(HistoryP)
        self.searchT.setGeometry(QtCore.QRect(1070, 90, 600, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.searchT.setFont(font)
        self.searchT.setObjectName("searchT")
        self.informationL = QtWidgets.QLabel(HistoryP)
        self.informationL.setGeometry(QtCore.QRect(540, 450, 500, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.informationL.setFont(font)
        self.informationL.setWordWrap(True)
        self.informationL.setObjectName("informationL")
        self.label = QtWidgets.QLabel(HistoryP)
        self.label.setGeometry(QtCore.QRect(430, 450, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(HistoryP)
        QtCore.QMetaObject.connectSlotsByName(HistoryP)

    def retranslateUi(self, HistoryP):
        _translate = QtCore.QCoreApplication.translate
        HistoryP.setWindowTitle(_translate("HistoryP", "Form"))
        self.searchB.setText(_translate("HistoryP", "搜索"))
        self.jumpToMainWindowP.setText(_translate("HistoryP", "返回首页"))
        self.informationL.setText(_translate("HistoryP", "获得的所有信息在此"))
        self.label.setText(_translate("HistoryP", "信息："))
