# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Like.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LikeP(object):
    def setupUi(self, LikeP):
        LikeP.setObjectName("LikeP")
        LikeP.resize(1920, 1080)
        self.imageL = QtWidgets.QLabel(LikeP)
        self.imageL.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.imageL.setText("")
        self.imageL.setPixmap(QtGui.QPixmap("../Image/patten2.png"))
        self.imageL.setObjectName("imageL")
        self.listWidget = QtWidgets.QListWidget(LikeP)
        self.listWidget.setGeometry(QtCore.QRect(60, 100, 1800, 900))
        self.listWidget.setObjectName("listWidget")
        self.jumpToMainWindowP = QtWidgets.QPushButton(LikeP)
        self.jumpToMainWindowP.setGeometry(QtCore.QRect(1740, 10, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.jumpToMainWindowP.setFont(font)
        self.jumpToMainWindowP.setStyleSheet("color: rgb(252, 204, 220);\n"
"background-color: rgb(7, 33, 58);")
        self.jumpToMainWindowP.setObjectName("jumpToMainWindowP")

        self.retranslateUi(LikeP)
        QtCore.QMetaObject.connectSlotsByName(LikeP)

    def retranslateUi(self, LikeP):
        _translate = QtCore.QCoreApplication.translate
        LikeP.setWindowTitle(_translate("LikeP", "Form"))
        self.jumpToMainWindowP.setText(_translate("LikeP", "返回首页"))
