# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginP(object):
    def setupUi(self, LoginP):
        LoginP.setObjectName("LoginP")
        LoginP.resize(1920, 1080)
        self.imageL = QtWidgets.QLabel(LoginP)
        self.imageL.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.imageL.setText("")
        self.imageL.setPixmap(QtGui.QPixmap("../Image/patten.png"))
        self.imageL.setScaledContents(True)
        self.imageL.setObjectName("imageL")
        self.verticalLayoutWidget = QtWidgets.QWidget(LoginP)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(2790, 729, 601, 180))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameT = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.usernameT.setFont(font)
        self.usernameT.setStyleSheet("color: rgb(0, 0, 0);")
        self.usernameT.setInputMethodHints(QtCore.Qt.ImhNone)
        self.usernameT.setObjectName("usernameT")
        self.verticalLayout.addWidget(self.usernameT)
        self.passwordT = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.passwordT.setFont(font)
        self.passwordT.setStyleSheet("color: rgb(0, 0, 0);")
        self.passwordT.setObjectName("passwordT")
        self.verticalLayout.addWidget(self.passwordT)
        self.label = QtWidgets.QLabel(LoginP)
        self.label.setGeometry(QtCore.QRect(2840, 330, 500, 300))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("color: rgb(46, 55, 112);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(1)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.loginB = QtWidgets.QPushButton(LoginP)
        self.loginB.setGeometry(QtCore.QRect(3060, 1000, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.loginB.setFont(font)
        self.loginB.setStyleSheet("color: rgb(46, 55, 112);")
        self.loginB.setObjectName("loginB")
        self.registerL = QtWidgets.QLabel(LoginP)
        self.registerL.setGeometry(QtCore.QRect(2790, 930, 599, 39))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        self.registerL.setFont(font)
        self.registerL.setAutoFillBackground(False)
        self.registerL.setStyleSheet("color: rgb(116, 113, 114);")
        self.registerL.setScaledContents(True)
        self.registerL.setObjectName("registerL")
        self.loginB_2 = QtWidgets.QPushButton(LoginP)
        self.loginB_2.setGeometry(QtCore.QRect(1310, 790, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.loginB_2.setFont(font)
        self.loginB_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"color: rgb(7, 33, 58);\n"
"")
        self.loginB_2.setObjectName("loginB_2")
        self.jumpToRegisterP = QtWidgets.QPushButton(LoginP)
        self.jumpToRegisterP.setGeometry(QtCore.QRect(1489, 710, 281, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.jumpToRegisterP.setFont(font)
        self.jumpToRegisterP.setStyleSheet("background-color: rgb(7, 33, 58);\n"
"color: rgb(252, 204, 220);")
        self.jumpToRegisterP.setObjectName("jumpToRegisterP")
        self.btn_keyboard = QtWidgets.QPushButton(LoginP)
        self.btn_keyboard.setGeometry(QtCore.QRect(830, 420, 120, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_keyboard.setFont(font)
        self.btn_keyboard.setStyleSheet("color: rgb(252, 204, 220);\n"
"background-color: rgb(7, 33, 58);")
        self.btn_keyboard.setObjectName("btn_keyboard")
        self.userT = QtWidgets.QLineEdit(LoginP)
        self.userT.setGeometry(QtCore.QRect(980, 370, 789, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(22)
        self.userT.setFont(font)
        self.userT.setStyleSheet("color: rgb(0, 0, 0);")
        self.userT.setClearButtonEnabled(True)
        self.userT.setObjectName("userT")
        self.pwdT = QtWidgets.QLineEdit(LoginP)
        self.pwdT.setGeometry(QtCore.QRect(980, 490, 789, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(22)
        self.pwdT.setFont(font)
        self.pwdT.setStyleSheet("color: rgb(0, 0, 0);")
        self.pwdT.setClearButtonEnabled(True)
        self.pwdT.setObjectName("pwdT")

        self.retranslateUi(LoginP)
        QtCore.QMetaObject.connectSlotsByName(LoginP)

    def retranslateUi(self, LoginP):
        _translate = QtCore.QCoreApplication.translate
        LoginP.setWindowTitle(_translate("LoginP", "Form"))
        self.usernameT.setHtml(_translate("LoginP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; color:#6a6a6a;\">username</span></p></body></html>"))
        self.passwordT.setHtml(_translate("LoginP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; color:#6a6a6a;\">password</span></p></body></html>"))
        self.label.setText(_translate("LoginP", "Pose Guide"))
        self.loginB.setText(_translate("LoginP", "登录"))
        self.registerL.setText(_translate("LoginP", "没有账号？快速注册"))
        self.loginB_2.setText(_translate("LoginP", "登录"))
        self.jumpToRegisterP.setText(_translate("LoginP", "没有账号？快速注册"))
        self.btn_keyboard.setText(_translate("LoginP", "键盘"))
        self.userT.setText(_translate("LoginP", "username"))
        self.pwdT.setText(_translate("LoginP", "password"))
