# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowP(object):
    def setupUi(self, MainWindowP):
        MainWindowP.setObjectName("MainWindowP")
        MainWindowP.resize(1920, 1080)
        self.imageL = QtWidgets.QLabel(MainWindowP)
        self.imageL.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.imageL.setText("")
        self.imageL.setPixmap(QtGui.QPixmap("../Image/MianWindow.png"))
        self.imageL.setScaledContents(True)
        self.imageL.setObjectName("imageL")
        self.jumpToChooseP = QtWidgets.QPushButton(MainWindowP)
        self.jumpToChooseP.setGeometry(QtCore.QRect(1260, 220, 143, 320))
        self.jumpToChooseP.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/button1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jumpToChooseP.setIcon(icon)
        self.jumpToChooseP.setIconSize(QtCore.QSize(143, 320))
        self.jumpToChooseP.setObjectName("jumpToChooseP")
        self.jumpToLikeP = QtWidgets.QPushButton(MainWindowP)
        self.jumpToLikeP.setGeometry(QtCore.QRect(1474, 324, 143, 320))
        self.jumpToLikeP.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Image/button2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jumpToLikeP.setIcon(icon1)
        self.jumpToLikeP.setIconSize(QtCore.QSize(143, 320))
        self.jumpToLikeP.setObjectName("jumpToLikeP")
        self.jumpToHistoryP = QtWidgets.QPushButton(MainWindowP)
        self.jumpToHistoryP.setGeometry(QtCore.QRect(1706, 416, 143, 320))
        self.jumpToHistoryP.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Image/button3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jumpToHistoryP.setIcon(icon2)
        self.jumpToHistoryP.setIconSize(QtCore.QSize(143, 320))
        self.jumpToHistoryP.setObjectName("jumpToHistoryP")
        self.jumpToLoginP = QtWidgets.QPushButton(MainWindowP)
        self.jumpToLoginP.setGeometry(QtCore.QRect(1720, 20, 161, 80))
        self.jumpToLoginP.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Image/loginB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jumpToLoginP.setIcon(icon3)
        self.jumpToLoginP.setIconSize(QtCore.QSize(161, 80))
        self.jumpToLoginP.setObjectName("jumpToLoginP")

        self.retranslateUi(MainWindowP)
        QtCore.QMetaObject.connectSlotsByName(MainWindowP)

    def retranslateUi(self, MainWindowP):
        _translate = QtCore.QCoreApplication.translate
        MainWindowP.setWindowTitle(_translate("MainWindowP", "Form"))
