# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

'''
Auth://作者 吴茜
Create date:///创建时间 2020.7.9
Update date://签入时间 2020.7.11
Discrip://此处须注明更新的详细内容
    以下为前端设计代码
    修改了控件的位置和名称
'''
class Ui_MainWindowP(object):
    def setupUi(self, MainWindowP):
        MainWindowP.setObjectName("MainWindowP")
        MainWindowP.resize(1920, 1080)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MainWindowP)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1090, 240, 581, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jumpToChooseP = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToChooseP.setFont(font)
        self.jumpToChooseP.setObjectName("jumpToChooseP")
        self.horizontalLayout.addWidget(self.jumpToChooseP)
        self.jumpToLikeP = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToLikeP.setFont(font)
        self.jumpToLikeP.setObjectName("jumpToLikeP")
        self.horizontalLayout.addWidget(self.jumpToLikeP)
        self.jumpToHistoryP = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToHistoryP.setFont(font)
        self.jumpToHistoryP.setObjectName("jumpToHistoryP")
        self.horizontalLayout.addWidget(self.jumpToHistoryP)
        self.jumpToLoginP = QtWidgets.QPushButton(MainWindowP)
        self.jumpToLoginP.setGeometry(QtCore.QRect(1740, 30, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToLoginP.setFont(font)
        self.jumpToLoginP.setObjectName("jumpToLoginP")

        self.retranslateUi(MainWindowP)
        QtCore.QMetaObject.connectSlotsByName(MainWindowP)

    def retranslateUi(self, MainWindowP):
        _translate = QtCore.QCoreApplication.translate
        MainWindowP.setWindowTitle(_translate("MainWindowP", "Form"))
        self.jumpToChooseP.setText(_translate("MainWindowP", "训练"))
        self.jumpToLikeP.setText(_translate("MainWindowP", "收藏夹"))
        self.jumpToHistoryP.setText(_translate("MainWindowP", "历史记录"))
        self.jumpToLoginP.setText(_translate("MainWindowP", "退出登录"))
