# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

'''
Auth://作者 吴茜
Create date:///创建时间 2020.7.9
Update date://签入时间 2020.7.12
Discrip://此处须注明更新的详细内容
    以下为前端设计代码
    修改了控件的位置和名称
'''
class Ui_RegitserP(object):
    def setupUi(self, RegitserP):
        RegitserP.setObjectName("RegitserP")
        RegitserP.resize(1920, 1080)
        self.imageL = QtWidgets.QLabel(RegitserP)
        self.imageL.setGeometry(QtCore.QRect(0, 0, 600, 1080))
        self.imageL.setText("")
        self.imageL.setPixmap(QtGui.QPixmap("../Image/15562886683298.png"))
        self.imageL.setScaledContents(True)
        self.imageL.setObjectName("imageL")
        self.registerB = QtWidgets.QPushButton(RegitserP)
        self.registerB.setGeometry(QtCore.QRect(1450, 900, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.registerB.setFont(font)
        self.registerB.setStyleSheet("color: rgb(46, 55, 112);")
        self.registerB.setObjectName("registerB")
        self.label = QtWidgets.QLabel(RegitserP)
        self.label.setGeometry(QtCore.QRect(1230, 170, 500, 200))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("color: rgb(46, 55, 112);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setLineWidth(1)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(RegitserP)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1180, 460, 601, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(50)
        self.vboxlayout.setObjectName("vboxlayout")
        self.emailT = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.emailT.setFont(font)
        self.emailT.setObjectName("emailT")
        self.vboxlayout.addWidget(self.emailT)
        self.usernameT = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.usernameT.setFont(font)
        self.usernameT.setStyleSheet("color: rgb(0, 0, 0);")
        self.usernameT.setInputMethodHints(QtCore.Qt.ImhNone)
        self.usernameT.setObjectName("usernameT")
        self.vboxlayout.addWidget(self.usernameT)
        self.passwordT = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.passwordT.setFont(font)
        self.passwordT.setStyleSheet("color: rgb(0, 0, 0);")
        self.passwordT.setObjectName("passwordT")
        self.vboxlayout.addWidget(self.passwordT)
        self.VpasswordT = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.VpasswordT.setFont(font)
        self.VpasswordT.setObjectName("VpasswordT")
        self.vboxlayout.addWidget(self.VpasswordT)
        self.jumpToLoginP = QtWidgets.QPushButton(RegitserP)
        self.jumpToLoginP.setGeometry(QtCore.QRect(670, 50, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.jumpToLoginP.setFont(font)
        self.jumpToLoginP.setObjectName("jumpToLoginP")

        self.retranslateUi(RegitserP)
        QtCore.QMetaObject.connectSlotsByName(RegitserP)

    def retranslateUi(self, RegitserP):
        _translate = QtCore.QCoreApplication.translate
        RegitserP.setWindowTitle(_translate("RegitserP", "Form"))
        self.registerB.setText(_translate("RegitserP", "注册"))
        self.label.setText(_translate("RegitserP", "Pose Guide"))
        self.emailT.setHtml(_translate("RegitserP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747172;\">email</span></p></body></html>"))
        self.usernameT.setHtml(_translate("RegitserP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; color:#6a6a6a;\">username</span></p></body></html>"))
        self.passwordT.setHtml(_translate("RegitserP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; color:#6a6a6a;\">password</span></p></body></html>"))
        self.VpasswordT.setHtml(_translate("RegitserP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Adobe Arabic\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747172;\">vertify password</span></p></body></html>"))
        self.jumpToLoginP.setText(_translate("RegitserP", "返回登录"))
