# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Score.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

'''
Auth://作者 吴茜
Create date:///创建时间 2020.7.9
Update date://签入时间 2020.7.12
Discrip://此处须注明更新的详细内容
    以下为前端设计代码
    增加了一些label控件以实现数据的显示结果
'''
class Ui_Score(object):
    def setupUi(self, Score):
        Score.setObjectName("Score")
        Score.resize(1920, 1080)
        self.jumpToMainWindowP = QtWidgets.QPushButton(Score)
        self.jumpToMainWindowP.setGeometry(QtCore.QRect(50, 60, 200, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.jumpToMainWindowP.setFont(font)
        self.jumpToMainWindowP.setObjectName("jumpToMainWindowP")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Score)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(720, 120, 191, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scoreL = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        self.scoreL.setFont(font)
        self.scoreL.setObjectName("scoreL")
        self.horizontalLayout.addWidget(self.scoreL)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Score)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(720, 210, 541, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.suggestionL = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(12)
        self.suggestionL.setFont(font)
        self.suggestionL.setWordWrap(True)
        self.suggestionL.setObjectName("suggestionL")
        self.horizontalLayout_2.addWidget(self.suggestionL)

        self.retranslateUi(Score)
        QtCore.QMetaObject.connectSlotsByName(Score)

    def retranslateUi(self, Score):
        _translate = QtCore.QCoreApplication.translate
        Score.setWindowTitle(_translate("Score", "Form"))
        self.jumpToMainWindowP.setText(_translate("Score", "返回首页"))
        self.label.setText(_translate("Score", "分数："))
        self.scoreL.setText(_translate("Score", "分数"))
        self.label_2.setText(_translate("Score", "建议："))
        self.suggestionL.setText(_translate("Score", "建议内容"))
