# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tabel.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabelP(object):
    def setupUi(self, TabelP):
        TabelP.setObjectName("TabelP")
        TabelP.resize(1920, 1080)
        self.imageL = QtWidgets.QLabel(TabelP)
        self.imageL.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.imageL.setText("")
        self.imageL.setPixmap(QtGui.QPixmap("Image/patten2.png"))
        self.imageL.setScaledContents(True)
        self.imageL.setObjectName("imageL")
        self.jumpToChooseP = QtWidgets.QPushButton(TabelP)
        self.jumpToChooseP.setGeometry(QtCore.QRect(1610, 50, 250, 80))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(20)
        self.jumpToChooseP.setFont(font)
        self.jumpToChooseP.setStyleSheet("color: rgb(252, 204, 220);\n"
"background-color: rgb(7, 33, 58);")
        self.jumpToChooseP.setObjectName("jumpToChooseP")

        self.retranslateUi(TabelP)
        QtCore.QMetaObject.connectSlotsByName(TabelP)

    def retranslateUi(self, TabelP):
        _translate = QtCore.QCoreApplication.translate
        TabelP.setWindowTitle(_translate("TabelP", "Form"))
        self.jumpToChooseP.setText(_translate("TabelP", "返回上一界面"))
